### ISSUE TITLE
Its not possible to select a config

### ISSUE THREAD

**Issue by nandoofz** [CatSnake11/Webpack-Ops#50]
I'm not sure if this could be the problem, but I have a `package.json` for two projects and each one has its own webpack config file. The structure would be something like this:

```
- src/
  - projectA/
  - projectB/
- config/
  - projectA/
     - webpack.config.js
  - projectB/
     - webpack.config.js
- package.json
```

Firts I selected the `package.json` file and then after clicking on "Select config" this happens:
![wbops](https://user-images.githubusercontent.com/2110047/55889301-44883300-5b87-11e9-8b13-c20f220b5fc2.png)

**Comment by davemarquess** [comment]
Webpack Ops is currently only built to work with `webpack.config` file stored in the root directory. 

Also, on the "Select Config" screen - it retrieves the config options from the options you have listed in the `scripts` property in your `package.json` file, e.g.,
```
{
  "name": "my_project",
  "version": "1.0.0",
  "description": "my project",
  "main": "src/index.js",
  "scripts": {
    "start": "webpack-dev-server --mode development --open",
    "build": "webpack --mode production --json > optimizedstats.json",
    "stats": "webpack --env production --profile --json > stats.json",
  },
...
```
![Screen Shot 2019-04-10 at 8 24 01 AM](https://user-images.githubusercontent.com/33312483/55891808-0e888600-5b6a-11e9-862b-198dc53d58f8.png)
